services:
  landing-prod:
    container_name: ai-up-landing-prod
    image: cr.yandex/crpqo933sodpue4v0r0n/landing:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND_BASE_URL: https://d5dtka2iprpa79g4qia0.apigw.yandexcloud.net/api
        NEXT_PUBLIC_BACKEND_BASE_URL: https://d5dtka2iprpa79g4qia0.apigw.yandexcloud.net/api
    restart: always
    ports:
      - 3000:3000
