services:
  landing-prod:
    container_name: ai-up-landing-prod
    image: cr.yandex/crpqo933sodpue4v0r0n/landing:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
