import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { fontInter,  fontEuclidCircular} from '../lib/fonts'
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          fontInter.variable,
          fontEuclidCircular.variable,
          'antialiased'
        )}
      >
        {children}
      </body>
    </html>
  );
}
